### ISSUE TITLE
NPM fails to install Chocolat

### ISSUE THREAD

**Issue by drawcard** [nicolas-t/Chocolat#57]
Dump of the error message:

```bash
05:44 $ npm install chocolat
npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.

> contextify@0.1.15 install /var/www/html/drawcard/wp-content/themes/sage-drawcard/node_modules/contextify
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/var/www/html/drawcard/wp-content/themes/sage-drawcard/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/chris/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/chris/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/chris/.node-gyp/7.5.0/include/node/v8.h:3292:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/chris/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/chris/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/chris/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/chris/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/chris/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/chris/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/chris/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/chris/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/chris/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/chris/.node-gyp/7.5.0/include/node/v8.h:26:0,
                 from /home/chris/.node-gyp/7.5.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/chris/.node-gyp/7.5.0/include/node/v8.h:2949:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/chris/.node-gyp/7.5.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
contextify.target.mk:94: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/var/www/html/drawcard/wp-content/themes/sage-drawcard/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/chris/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/home/chris/.nvm/versions/node/v7.5.0/bin/node" "/home/chris/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/drawcard/wp-content/themes/sage-drawcard/node_modules/contextify
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
sage@9.0.0-beta.2 /var/www/html/drawcard/wp-content/themes/sage-drawcard
└─┬ bs-html-injector@3.0.3
  └─┬ dom-compare-temp@0.1.0
    ├── argparse@1.0.9
    └── colors@1.1.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/home/chris/.nvm/versions/node/v7.5.0/bin/node" "/home/chris/.nvm/versions/node/v7.5.0/bin/npm" "install" "chocolat"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
```

**Comment by nicolas-t** [comment]
thanks a lot !

should be fixed now, try `npm install chocolat` and tell me.

related release is here : https://github.com/nicolas-t/Chocolat/releases/tag/0.4.16

best
